import Head from "next/head";
import React from "react";

const BasicLayout = (props) => {
  return (
    <>
      <Head>
        <title>{props.title || "Scanocular Dashboard"}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="shortcut icon" href="/favicon.ico" />
        <link
          rel="icon"
          sizes="16x16 32x32 64x64"
          href="/assets/favicon/favicon.ico"
        />
      </Head>
      <div className="content">{props.children}</div>
    </>
  );
};

export default BasicLayout;
